---
- hosts: localhost
  gather_facts: false

  vars:
    list1:
      - item1
      - item2
      - item3
      - item4

    list2:
      - item3
      - item4
      - item5
      - item6

  tasks:
    - name: Find common items in lists
      set_fact:
        common_items: "{{ list1 | intersect(list2) }}"
      when: list1 and list2

    - name: Format list of common items
      set_fact:
        common_items_formatted: |
          {% if common_items %}
          The following items are common between list1 and list2:
          {% for item in common_items %}
          - {{ item }}
          {% endfor %}
          {% else %}
          There are no common items between list1 and list2.
          {% endif %}

    - name: Send email notification of common items
      mail:
        to: "you@example.com"
        subject: "Common items between list1 and list2"
        body: "{{ common_items_formatted }}"
      when: common_items
